image:
  - Visual Studio 2017
clone_folder: c:\projects\source
build_script:
  - cmd: mkdir build
  - cmd: cd build  
  - cmd: cmake c:\projects\source\CPP-test\cmake\t1 -G "Visual Studio 15"
  - cmd: cmake --build . --config "Debug"
